### Numpy basics

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```



2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [47]:
rand = np.random.random(60).reshape(10,6)
print(rand, "\n")
mask = rand < 0.1
print(mask, "\n")
for i in range(len(rand)):
    if np.any([mask[i, :]]):
        rand[i] = 0
print(rand)

[[0.56506097 0.79151189 0.46180163 0.68975343 0.41280287 0.16909145]
 [0.24543494 0.63510934 0.65258909 0.88026575 0.36741595 0.67247235]
 [0.0832831  0.7051896  0.50713738 0.38788217 0.9676276  0.98037581]
 [0.99799149 0.62878533 0.44235885 0.90990744 0.02774497 0.97413432]
 [0.20205841 0.62351667 0.50394564 0.87940811 0.86548032 0.84135274]
 [0.19813512 0.04158184 0.36083617 0.39263535 0.53953537 0.74329423]
 [0.77359639 0.30969704 0.92558756 0.95381974 0.47973567 0.36075971]
 [0.3688129  0.52728453 0.66006477 0.94771167 0.89255321 0.41998329]
 [0.4055521  0.6036641  0.89455476 0.80840891 0.57389725 0.22244527]
 [0.02736347 0.05199363 0.05709103 0.99128842 0.48620861 0.25598186]] 

[[False False False False False False]
 [False False False False False False]
 [ True False False False False False]
 [False False False False  True False]
 [False False False False False False]
 [False  True False False False False]
 [False False False False False False]
 [False False False False False Fa

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

In [24]:
a = np.linspace(0, 2*np.pi, 100)
# print(a[::10])
# print(a[::-1])
mask = np.abs(np.sin(a) - np.cos(a)) < 0.1
a_filtered = a[mask]
a_filtered


array([0.76159822, 0.82506474, 3.87145761, 3.93492413])

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.